version: '3.4'

services:
  ci-build:
    image: mcr.microsoft.com/dotnet/core/aspnet:3.1
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./AspNetCore.Identity.Cassandra.sln && dotnet publish ./AspNetCore.Identity.Cassandra.sln -c Release -o ./obj/Docker/publish"
